version: '3'

vars:
  IOSEVKA_DIR: /tmp/Iosevka
  BUILD_PLAN: DigitalGecko
  DIST_DIR: ./dist

tasks:
  clone:
    desc: Clone Iosevka repository
    cmds:
      - git clone --depth 1 https://github.com/be5invis/Iosevka.git {{.IOSEVKA_DIR}}
    status:
      - test -d {{.IOSEVKA_DIR}}

  install:
    desc: Install Iosevka dependencies
    deps:
      - clone
    dir: "{{.IOSEVKA_DIR}}"
    cmds:
      - npm install
    status:
      - test -d {{.IOSEVKA_DIR}}/node_modules

  setup-config:
    desc: Copy custom configuration to Iosevka build directory
    deps:
      - install
    cmds:
      - cp digitalgecko.toml {{.IOSEVKA_DIR}}/private-build-plans.toml

  build:
    desc: Build Digital Gecko font
    deps:
      - setup-config
    dir: "{{.IOSEVKA_DIR}}"
    cmds:
      - npm run build -- contents::{{.BUILD_PLAN}}
      - npm run build -- ttc::{{.BUILD_PLAN}}
      - npm run build -- super-ttc::{{.BUILD_PLAN}}

  copy-fonts:
    desc: Copy and organize built fonts to project dist directory
    deps:
      - build
    cmds:
      - mkdir -p {{.DIST_DIR}}/ttf {{.DIST_DIR}}/woff2 {{.DIST_DIR}}/ttc
      - |
        for file in {{.IOSEVKA_DIR}}/dist/DigitalGecko/TTF-Unhinted/*.ttf; do
          [ -f "$file" ] && cp "$file" "{{.DIST_DIR}}/ttf/$(basename "$file" .ttf)-Unhinted.ttf"
        done
      - |
        for file in {{.IOSEVKA_DIR}}/dist/DigitalGecko/TTF/*.ttf; do
          [ -f "$file" ] && cp "$file" "{{.DIST_DIR}}/ttf/$(basename "$file")"
        done
      - |
        for file in {{.IOSEVKA_DIR}}/dist/DigitalGecko/WOFF2-Unhinted/*.woff2; do
          [ -f "$file" ] && cp "$file" "{{.DIST_DIR}}/woff2/$(basename "$file" .woff2)-Unhinted.woff2"
        done
      - |
        for file in {{.IOSEVKA_DIR}}/dist/DigitalGecko/WOFF2/*.woff2; do
          [ -f "$file" ] && cp "$file" "{{.DIST_DIR}}/woff2/$(basename "$file")"
        done
      - find {{.IOSEVKA_DIR}}/dist/.ttc -name "*.ttc" -type f -exec cp {} {{.DIST_DIR}}/ttc/ \; 2>/dev/null || true
      - find {{.IOSEVKA_DIR}}/dist/.super-ttc -name "*.ttc" -type f -exec cp {} {{.DIST_DIR}}/ttc/ \; 2>/dev/null || true
      - echo "TTF files:" && ls -1 {{.DIST_DIR}}/ttf/ | wc -l
      - echo "WOFF2 files:" && ls -1 {{.DIST_DIR}}/woff2/ | wc -l
      - echo "TTC files:" && ls -1 {{.DIST_DIR}}/ttc/ 2>/dev/null | wc -l || echo "0"

  all:
    desc: Complete build process (clone, install, build, copy)
    deps:
      - copy-fonts

  clean:
    desc: Clean build artifacts and temporary files
    cmds:
      - rm -rf {{.DIST_DIR}}
      - rm -rf {{.IOSEVKA_DIR}}

  clean-dist:
    desc: Clean only dist directory
    cmds:
      - rm -rf {{.DIST_DIR}}

  list-fonts:
    desc: List built fonts in dist directory
    cmds:
      - test -d {{.DIST_DIR}} && (echo "TTF:" && ls {{.DIST_DIR}}/ttf/ 2>/dev/null | wc -l && echo "WOFF2:" && ls {{.DIST_DIR}}/woff2/ 2>/dev/null | wc -l && echo "TTC:" && ls {{.DIST_DIR}}/ttc/ 2>/dev/null | wc -l) || echo "No fonts built yet. Run 'task all' first."
